-- ============================================================
-- Catálogo mundial de exames diagnósticos (exam_catalog)
-- ============================================================
-- Uma tabela única (conceito do exame) com:
--   * exam_catalog             -> o exame (id, tipo, categoria)
--   * exam_catalog_translations-> nome do exame por locale
--   * exam_catalog_codes       -> código oficial do nomenclador por país
--       (BR: TUSS/AMB | PY: IPS | AR/ES: nomencladores nacionais | US: CPT)
--
-- O front busca pelo locale ativo (pt-BR, pt-PT, es-AR, es-PY, es, en)
-- e pode abrir registros de exam_requests para o conceito do catálogo.
-- ============================================================

-- 1) Tabela principal do catálogo
CREATE TABLE IF NOT EXISTS public.exam_catalog (
  id text PRIMARY KEY,
  exam_type text NOT NULL CHECK (exam_type IN ('laboratorio','imagem','anatomia_patologica','outro')),
  category text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2) Traduções por locale
CREATE TABLE IF NOT EXISTS public.exam_catalog_translations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id text NOT NULL REFERENCES public.exam_catalog(id) ON DELETE CASCADE,
  locale text NOT NULL CHECK (locale IN ('pt-BR','pt-PT','es-AR','es-PY','es','en')),
  name text NOT NULL,
  UNIQUE (catalog_id, locale)
);
CREATE INDEX IF NOT EXISTS idx_exam_catalog_translations_locale
  ON public.exam_catalog_translations (locale);

-- 3) Códigos oficiais por país (nomencladores)
CREATE TABLE IF NOT EXISTS public.exam_catalog_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_id text NOT NULL REFERENCES public.exam_catalog(id) ON DELETE CASCADE,
  country text NOT NULL CHECK (country IN ('BR','PT','AR','PY','ES','US')),
  code text NOT NULL,
  source text,
  UNIQUE (catalog_id, country)
);
CREATE INDEX IF NOT EXISTS idx_exam_catalog_codes_country
  ON public.exam_catalog_codes (country);

-- 4) Sequência + RPC para IDs (regra obrigatória do AGENTS.md)
CREATE SEQUENCE IF NOT EXISTS public.seq_exam_catalog START 1;

CREATE OR REPLACE FUNCTION public.next_exam_catalog_id()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE v int;
BEGIN
  v := nextval('seq_exam_catalog');
  RETURN 'ecat_' || lpad(v::text, 4, '0');
END$$;

-- 5) Vínculo da solicitação de exame com o catálogo
ALTER TABLE public.exam_requests
  ADD COLUMN IF NOT EXISTS exam_catalog_id text
    REFERENCES public.exam_catalog(id) ON DELETE SET NULL;

-- 6) Row Level Security (leitura pública, escrita autenticada)
ALTER TABLE public.exam_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_catalog_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_catalog_codes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog'
                   AND policyname='exam_catalog_select_anon') THEN
    CREATE POLICY exam_catalog_select_anon
      ON public.exam_catalog FOR SELECT TO anon USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog'
                   AND policyname='Allow authenticated exam_catalog') THEN
    CREATE POLICY "Allow authenticated exam_catalog"
      ON public.exam_catalog TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog_translations'
                   AND policyname='exam_catalog_translations_select_anon') THEN
    CREATE POLICY exam_catalog_translations_select_anon
      ON public.exam_catalog_translations FOR SELECT TO anon USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog_translations'
                   AND policyname='Allow authenticated exam_catalog_translations') THEN
    CREATE POLICY "Allow authenticated exam_catalog_translations"
      ON public.exam_catalog_translations TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog_codes'
                   AND policyname='exam_catalog_codes_select_anon') THEN
    CREATE POLICY exam_catalog_codes_select_anon
      ON public.exam_catalog_codes FOR SELECT TO anon USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies
                 WHERE schemaname='public' AND tablename='exam_catalog_codes'
                   AND policyname='Allow authenticated exam_catalog_codes') THEN
    CREATE POLICY "Allow authenticated exam_catalog_codes"
      ON public.exam_catalog_codes TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;