-- ============================================================
-- Seed do catálogo mundial de exames (100 exames comuns)
-- ============================================================
-- 6.4 do objetivo: "Cadastro de pedidos com códigos do nomenclador
-- do prestador ou convencional". Aqui curamos 100 exames dos 4 tipos
-- (laboratorio, imagem, anatomia_patologica, outro) traduzidos em:
--   pt-BR | pt-PT | es-AR | es-PY | es | en
--
-- exam_catalog_codes fica vazio de propósito: os códigos oficiais
-- (TUSS/AMB, IPS, CPT...) devem ser importados de arquivos oficiais
-- (o código é nacional; o exame é o mesmo).
-- ============================================================

INSERT INTO public.exam_catalog (id, exam_type, category) VALUES
('ecat_0001','laboratorio','hematologia'),
('ecat_0002','laboratorio','bioquimica'),
('ecat_0003','laboratorio','bioquimica'),
('ecat_0004','laboratorio','lipidograma'),
('ecat_0005','laboratorio','lipidograma'),
('ecat_0006','laboratorio','lipidograma'),
('ecat_0007','laboratorio','lipidograma'),
('ecat_0008','laboratorio','bioquimica'),
('ecat_0009','laboratorio','bioquimica'),
('ecat_0010','laboratorio','bioquimica'),
('ecat_0011','laboratorio','enzimas'),
('ecat_0012','laboratorio','enzimas'),
('ecat_0013','laboratorio','enzimas'),
('ecat_0014','laboratorio','bioquimica'),
('ecat_0015','laboratorio','enzimas'),
('ecat_0016','laboratorio','hormonios'),
('ecat_0017','laboratorio','hormonios'),
('ecat_0018','laboratorio','hormonios'),
('ecat_0019','laboratorio','hormonios'),
('ecat_0020','laboratorio','bioquimica'),
('ecat_0021','laboratorio','bioquimica'),
('ecat_0022','laboratorio','hormonios'),
('ecat_0023','laboratorio','bioquimica'),
('ecat_0024','laboratorio','bioquimica'),
('ecat_0025','laboratorio','inflamacao'),
('ecat_0026','laboratorio','inflamacao'),
('ecat_0027','laboratorio','eletrolitos'),
('ecat_0028','laboratorio','eletrolitos'),
('ecat_0029','laboratorio','eletrolitos'),
('ecat_0030','laboratorio','eletrolitos'),
('ecat_0031','laboratorio','urina'),
('ecat_0032','laboratorio','urina'),
('ecat_0033','laboratorio','microbiologia'),
('ecat_0034','laboratorio','hormonios'),
('ecat_0035','laboratorio','coagulacao'),
('ecat_0036','laboratorio','enzimas'),
('ecat_0037','laboratorio','enzimas'),
('ecat_0038','laboratorio','bioquimica'),
('ecat_0039','laboratorio','sorologia'),
('ecat_0040','laboratorio','sorologia'),
('ecat_0041','laboratorio','sorologia'),
('ecat_0042','laboratorio','sorologia'),
('ecat_0043','laboratorio','sorologia'),
('ecat_0044','laboratorio','parasitologia'),
('ecat_0045','laboratorio','bioquimica'),
('ecat_0046','laboratorio','bioquimica'),
('ecat_0047','laboratorio','enzimas'),
('ecat_0048','laboratorio','enzimas'),
('ecat_0049','laboratorio','enzimas'),
('ecat_0050','laboratorio','enzimas'),
('ecat_0051','imagem','radiologia'),
('ecat_0052','imagem','radiologia'),
('ecat_0053','imagem','radiologia'),
('ecat_0054','imagem','radiologia'),
('ecat_0055','imagem','radiologia'),
('ecat_0056','imagem','radiologia'),
('ecat_0057','imagem','mamografia'),
('ecat_0058','imagem','ultrassonografia'),
('ecat_0059','imagem','ultrassonografia'),
('ecat_0060','imagem','ultrassonografia'),
('ecat_0061','imagem','ultrassonografia'),
('ecat_0062','imagem','ultrassonografia'),
('ecat_0063','imagem','ultrassonografia'),
('ecat_0064','imagem','tomografia'),
('ecat_0065','imagem','tomografia'),
('ecat_0066','imagem','tomografia'),
('ecat_0067','imagem','tomografia'),
('ecat_0068','imagem','ressonancia'),
('ecat_0069','imagem','ressonancia'),
('ecat_0070','imagem','ressonancia'),
('ecat_0071','imagem','ressonancia'),
('ecat_0072','imagem','cardiologia'),
('ecat_0073','imagem','cardiologia'),
('ecat_0074','imagem','vascular'),
('ecat_0075','imagem','densitometria'),
('ecat_0076','imagem','tomografia'),
('ecat_0077','anatomia_patologica','histopatologia'),
('ecat_0078','anatomia_patologica','citopatologia'),
('ecat_0079','anatomia_patologica','imuno'),
('ecat_0080','anatomia_patologica','histopatologia'),
('ecat_0081','anatomia_patologica','citopatologia'),
('ecat_0082','anatomia_patologica','citopatologia'),
('ecat_0083','anatomia_patologica','histopatologia'),
('ecat_0084','anatomia_patologica','histopatologia'),
('ecat_0085','anatomia_patologica','imuno'),
('ecat_0086','anatomia_patologica','histopatologia'),
('ecat_0087','outro','cardiologia'),
('ecat_0088','outro','neurologia'),
('ecat_0089','outro','neurologia'),
('ecat_0090','outro','pneumologia'),
('ecat_0091','outro','cardiologia'),
('ecat_0092','outro','cardiologia'),
('ecat_0093','outro','cardiologia'),
('ecat_0094','outro','pneumologia'),
('ecat_0095','outro','neonatologia'),
('ecat_0096','outro','otorrinolaringologia'),
('ecat_0097','outro','gastroenterologia'),
('ecat_0098','outro','gastroenterologia'),
('ecat_0099','outro','pneumologia'),
('ecat_0100','outro','alergologia');

INSERT INTO public.exam_catalog_translations (catalog_id, locale, name) VALUES
('ecat_0001','pt-BR','Hemograma completo'),
('ecat_0001','pt-PT','Hemograma completo'),
('ecat_0001','es-AR','Hemograma completo'),
('ecat_0001','es-PY','Hemograma completo'),
('ecat_0001','es','Hemograma completo'),
('ecat_0001','en','Complete blood count (CBC)'),
('ecat_0002','pt-BR','Glicemia em jejum'),
('ecat_0002','pt-PT','Glicémia em jejum'),
('ecat_0002','es-AR','Glucemia en ayunas'),
('ecat_0002','es-PY','Glucemia en ayunas'),
('ecat_0002','es','Glucemia en ayunas'),
('ecat_0002','en','Fasting blood glucose'),
('ecat_0003','pt-BR','Hemoglobina glicada (HbA1c)'),
('ecat_0003','pt-PT','Hemoglobina glicada (HbA1c)'),
('ecat_0003','es-AR','Hemoglobina glicada (HbA1c)'),
('ecat_0003','es-PY','Hemoglobina glicada (HbA1c)'),
('ecat_0003','es','Hemoglobina glucosilada (HbA1c)'),
('ecat_0003','en','Glycated hemoglobin (HbA1c)'),
('ecat_0004','pt-BR','Colesterol total'),
('ecat_0004','pt-PT','Colesterol total'),
('ecat_0004','es-AR','Colesterol total'),
('ecat_0004','es-PY','Colesterol total'),
('ecat_0004','es','Colesterol total'),
('ecat_0004','en','Total cholesterol'),
('ecat_0005','pt-BR','HDL colesterol'),
('ecat_0005','pt-PT','HDL colesterol'),
('ecat_0005','es-AR','Colesterol HDL'),
('ecat_0005','es-PY','Colesterol HDL'),
('ecat_0005','es','Colesterol HDL'),
('ecat_0005','en','HDL cholesterol'),
('ecat_0006','pt-BR','LDL colesterol'),
('ecat_0006','pt-PT','LDL colesterol'),
('ecat_0006','es-AR','Colesterol LDL'),
('ecat_0006','es-PY','Colesterol LDL'),
('ecat_0006','es','Colesterol LDL'),
('ecat_0006','en','LDL cholesterol'),
('ecat_0007','pt-BR','Triglicerídeos'),
('ecat_0007','pt-PT','Triglicéridos'),
('ecat_0007','es-AR','Triglicéridos'),
('ecat_0007','es-PY','Triglicéridos'),
('ecat_0007','es','Triglicéridos'),
('ecat_0007','en','Triglycerides'),
('ecat_0008','pt-BR','Creatinina'),
('ecat_0008','pt-PT','Creatinina'),
('ecat_0008','es-AR','Creatinina'),
('ecat_0008','es-PY','Creatinina'),
('ecat_0008','es','Creatinina'),
('ecat_0008','en','Creatinine'),
('ecat_0009','pt-BR','Ureia'),
('ecat_0009','pt-PT','Ureia'),
('ecat_0009','es-AR','Urea'),
('ecat_0009','es-PY','Urea'),
('ecat_0009','es','Urea'),
('ecat_0009','en','Blood urea nitrogen (BUN)'),
('ecat_0010','pt-BR','Ácido úrico'),
('ecat_0010','pt-PT','Ácido úrico'),
('ecat_0010','es-AR','Ácido úrico'),
('ecat_0010','es-PY','Ácido úrico'),
('ecat_0010','es','Ácido úrico'),
('ecat_0010','en','Uric acid'),
('ecat_0011','pt-BR','TGO/AST (Transaminase glutâmico-oxalacética)'),
('ecat_0011','pt-PT','TGO/AST (Transaminase glutâmico-oxalacética)'),
('ecat_0011','es-AR','TGO/AST (Transaminasa glutámico-oxalacética)'),
('ecat_0011','es-PY','TGO/AST (Transaminasa glutámico-oxalacética)'),
('ecat_0011','es','TGO/AST (Transaminasa glutámico-oxalacética)'),
('ecat_0011','en','AST (Aspartate aminotransferase)'),
('ecat_0012','pt-BR','TGP/ALT (Transaminase glutâmico-pirúvica)'),
('ecat_0012','pt-PT','TGP/ALT (Transaminase glutâmico-pirúvica)'),
('ecat_0012','es-AR','TGP/ALT (Transaminasa glutámico-pirúvica)'),
('ecat_0012','es-PY','TGP/ALT (Transaminasa glutámico-pirúvica)'),
('ecat_0012','es','TGP/ALT (Transaminasa glutámico-pirúvica)'),
('ecat_0012','en','ALT (Alanine aminotransferase)'),
('ecat_0013','pt-BR','Gama-GT (Gama-glutamiltransferase)'),
('ecat_0013','pt-PT','Gama-GT (Gama-glutamiltransferase)'),
('ecat_0013','es-AR','Gamma-GT (Gamma-glutamiltransferasa)'),
('ecat_0013','es-PY','Gamma-GT (Gamma-glutamiltransferasa)'),
('ecat_0013','es','Gamma-GT (Gamma-glutamiltransferasa)'),
('ecat_0013','en','GGT (Gamma-glutamyl transferase)'),
('ecat_0014','pt-BR','Bilirrubinas totais e frações'),
('ecat_0014','pt-PT','Bilirrubinas totais e frações'),
('ecat_0014','es-AR','Bilirrubina total y fracciones'),
('ecat_0014','es-PY','Bilirrubina total y fracciones'),
('ecat_0014','es','Bilirrubina total y fracciones'),
('ecat_0014','en','Total and fractionated bilirubin'),
('ecat_0015','pt-BR','Fosfatase alcalina'),
('ecat_0015','pt-PT','Fosfatase alcalina'),
('ecat_0015','es-AR','Fosfatasa alcalina'),
('ecat_0015','es-PY','Fosfatasa alcalina'),
('ecat_0015','es','Fosfatasa alcalina'),
('ecat_0015','en','Alkaline phosphatase'),
('ecat_0016','pt-BR','TSH (Hormônio tireoestimulante)'),
('ecat_0016','pt-PT','TSH (Hormona tireoestimulante)'),
('ecat_0016','es-AR','TSH (Hormona estimulante de la tiroides)'),
('ecat_0016','es-PY','TSH (Hormona estimulante de la tiroides)'),
('ecat_0016','es','TSH (Hormona estimulante de la tiroides)'),
('ecat_0016','en','TSH (Thyroid stimulating hormone)'),
('ecat_0017','pt-BR','T4 livre'),
('ecat_0017','pt-PT','T4 livre'),
('ecat_0017','es-AR','T4 libre'),
('ecat_0017','es-PY','T4 libre'),
('ecat_0017','es','T4 libre'),
('ecat_0017','en','Free T4'),
('ecat_0018','pt-BR','T3 livre'),
('ecat_0018','pt-PT','T3 livre'),
('ecat_0018','es-AR','T3 libre'),
('ecat_0018','es-PY','T3 libre'),
('ecat_0018','es','T3 libre'),
('ecat_0018','en','Free T3'),
('ecat_0019','pt-BR','PSA total'),
('ecat_0019','pt-PT','PSA total'),
('ecat_0019','es-AR','PSA total'),
('ecat_0019','es-PY','PSA total'),
('ecat_0019','es','PSA total'),
('ecat_0019','en','Total PSA'),
('ecat_0020','pt-BR','Ferritina'),
('ecat_0020','pt-PT','Ferritina'),
('ecat_0020','es-AR','Ferritina'),
('ecat_0020','es-PY','Ferritina'),
('ecat_0020','es','Ferritina'),
('ecat_0020','en','Ferritin'),
('ecat_0021','pt-BR','Ferro sérico'),
('ecat_0021','pt-PT','Ferro sérico'),
('ecat_0021','es-AR','Hierro sérico'),
('ecat_0021','es-PY','Hierro sérico'),
('ecat_0021','es','Hierro sérico'),
('ecat_0021','en','Serum iron'),
('ecat_0022','pt-BR','Vitamina D (25-hidroxi)'),
('ecat_0022','pt-PT','Vitamina D (25-hidroxi)'),
('ecat_0022','es-AR','Vitamina D (25-hidroxi)'),
('ecat_0022','es-PY','Vitamina D (25-hidroxi)'),
('ecat_0022','es','Vitamina D (25-hidroxi)'),
('ecat_0022','en','Vitamin D (25-hydroxy)'),
('ecat_0023','pt-BR','Vitamina B12'),
('ecat_0023','pt-PT','Vitamina B12'),
('ecat_0023','es-AR','Vitamina B12'),
('ecat_0023','es-PY','Vitamina B12'),
('ecat_0023','es','Vitamina B12'),
('ecat_0023','en','Vitamin B12'),
('ecat_0024','pt-BR','Ácido fólico'),
('ecat_0024','pt-PT','Ácido fólico'),
('ecat_0024','es-AR','Ácido fólico'),
('ecat_0024','es-PY','Ácido fólico'),
('ecat_0024','es','Ácido fólico'),
('ecat_0024','en','Folate (folic acid)'),
('ecat_0025','pt-BR','Proteína C reativa (PCR)'),
('ecat_0025','pt-PT','Proteína C reativa (PCR)'),
('ecat_0025','es-AR','Proteína C reactiva (PCR)'),
('ecat_0025','es-PY','Proteína C reactiva (PCR)'),
('ecat_0025','es','Proteína C reactiva (PCR)'),
('ecat_0025','en','C-reactive protein (CRP)'),
('ecat_0026','pt-BR','VHS (Velocidade de hemossedimentação)'),
('ecat_0026','pt-PT','VHS (Velocidade de hemossedimentação)'),
('ecat_0026','es-AR','VSG (Velocidad de sedimentación globular)'),
('ecat_0026','es-PY','VSG (Velocidad de sedimentación globular)'),
('ecat_0026','es','VSG (Velocidad de sedimentación globular)'),
('ecat_0026','en','ESR (Erythrocyte sedimentation rate)'),
('ecat_0027','pt-BR','Sódio'),
('ecat_0027','pt-PT','Sódio'),
('ecat_0027','es-AR','Sodio'),
('ecat_0027','es-PY','Sodio'),
('ecat_0027','es','Sodio'),
('ecat_0027','en','Sodium'),
('ecat_0028','pt-BR','Potássio'),
('ecat_0028','pt-PT','Potássio'),
('ecat_0028','es-AR','Potasio'),
('ecat_0028','es-PY','Potasio'),
('ecat_0028','es','Potasio'),
('ecat_0028','en','Potassium'),
('ecat_0029','pt-BR','Cálcio'),
('ecat_0029','pt-PT','Cálcio'),
('ecat_0029','es-AR','Calcio'),
('ecat_0029','es-PY','Calcio'),
('ecat_0029','es','Calcio'),
('ecat_0029','en','Calcium'),
('ecat_0030','pt-BR','Magnésio'),
('ecat_0030','pt-PT','Magnésio'),
('ecat_0030','es-AR','Magnesio'),
('ecat_0030','es-PY','Magnesio'),
('ecat_0030','es','Magnesio'),
('ecat_0030','en','Magnesium'),
('ecat_0031','pt-BR','Urina tipo I (EAS)'),
('ecat_0031','pt-PT','Urina tipo I (EAS)'),
('ecat_0031','es-AR','Análisis de orina (EAS)'),
('ecat_0031','es-PY','Análisis de orina (EAS)'),
('ecat_0031','es','Análisis de orina (EAS)'),
('ecat_0031','en','Urinalysis (EAS)'),
('ecat_0032','pt-BR','Urocultura com antibiograma'),
('ecat_0032','pt-PT','Urocultura com antibiograma'),
('ecat_0032','es-AR','Urocultivo con antibiograma'),
('ecat_0032','es-PY','Urocultivo con antibiograma'),
('ecat_0032','es','Urocultivo con antibiograma'),
('ecat_0032','en','Urine culture with antibiogram'),
('ecat_0033','pt-BR','Hemocultura'),
('ecat_0033','pt-PT','Hemocultura'),
('ecat_0033','es-AR','Hemocultivo'),
('ecat_0033','es-PY','Hemocultivo'),
('ecat_0033','es','Hemocultivo'),
('ecat_0033','en','Blood culture'),
('ecat_0034','pt-BR','Beta-hCG (teste de gravidez)'),
('ecat_0034','pt-PT','Beta-hCG (teste de gravidez)'),
('ecat_0034','es-AR','Beta-hCG (test de embarazo)'),
('ecat_0034','es-PY','Beta-hCG (test de embarazo)'),
('ecat_0034','es','Beta-hCG (test de embarazo)'),
('ecat_0034','en','Beta-hCG (pregnancy test)'),
('ecat_0035','pt-BR','D-dímero'),
('ecat_0035','pt-PT','D-dímero'),
('ecat_0035','es-AR','Dímero D'),
('ecat_0035','es-PY','Dímero D'),
('ecat_0035','es','Dímero D'),
('ecat_0035','en','D-dimer'),
('ecat_0036','pt-BR','Troponina I'),
('ecat_0036','pt-PT','Troponina I'),
('ecat_0036','es-AR','Troponina I'),
('ecat_0036','es-PY','Troponina I'),
('ecat_0036','es','Troponina I'),
('ecat_0036','en','Troponin I'),
('ecat_0037','pt-BR','CK-MB'),
('ecat_0037','pt-PT','CK-MB'),
('ecat_0037','es-AR','CK-MB'),
('ecat_0037','es-PY','CK-MB'),
('ecat_0037','es','CK-MB'),
('ecat_0037','en','CK-MB'),
('ecat_0038','pt-BR','Lactato'),
('ecat_0038','pt-PT','Lactato'),
('ecat_0038','es-AR','Lactato'),
('ecat_0038','es-PY','Lactato'),
('ecat_0038','es','Lactato'),
('ecat_0038','en','Lactate'),
('ecat_0039','pt-BR','Sorologia HIV'),
('ecat_0039','pt-PT','Serologia VIH'),
('ecat_0039','es-AR','Serología VIH'),
('ecat_0039','es-PY','Serología VIH'),
('ecat_0039','es','Serología VIH'),
('ecat_0039','en','HIV serology'),
('ecat_0040','pt-BR','Sorologia hepatite B (HBsAg/anti-HBs)'),
('ecat_0040','pt-PT','Serologia hepatite B (HBsAg/anti-HBs)'),
('ecat_0040','es-AR','Serología hepatitis B (HBsAg/anti-HBs)'),
('ecat_0040','es-PY','Serología hepatitis B (HBsAg/anti-HBs)'),
('ecat_0040','es','Serología hepatitis B (HBsAg/anti-HBs)'),
('ecat_0040','en','Hepatitis B serology (HBsAg/anti-HBs)'),
('ecat_0041','pt-BR','Sorologia hepatite C'),
('ecat_0041','pt-PT','Serologia hepatite C'),
('ecat_0041','es-AR','Serología hepatitis C'),
('ecat_0041','es-PY','Serología hepatitis C'),
('ecat_0041','es','Serología hepatitis C'),
('ecat_0041','en','Hepatitis C serology'),
('ecat_0042','pt-BR','VDRL (sífilis)'),
('ecat_0042','pt-PT','VDRL (sífilis)'),
('ecat_0042','es-AR','VDRL (sífilis)'),
('ecat_0042','es-PY','VDRL (sífilis)'),
('ecat_0042','es','VDRL (sífilis)'),
('ecat_0042','en','VDRL (syphilis)'),
('ecat_0043','pt-BR','Sorologia dengue (NS1/IgM/IgG)'),
('ecat_0043','pt-PT','Serologia dengue (NS1/IgM/IgG)'),
('ecat_0043','es-AR','Serología dengue (NS1/IgM/IgG)'),
('ecat_0043','es-PY','Serología dengue (NS1/IgM/IgG)'),
('ecat_0043','es','Serología dengue (NS1/IgM/IgG)'),
('ecat_0043','en','Dengue serology (NS1/IgM/IgG)'),
('ecat_0044','pt-BR','Parasitológico de fezes'),
('ecat_0044','pt-PT','Exame parasitológico de fezes'),
('ecat_0044','es-AR','Parasitológico de heces'),
('ecat_0044','es-PY','Parasitológico de heces'),
('ecat_0044','es','Parasitológico de heces'),
('ecat_0044','en','Stool ova and parasites'),
('ecat_0045','pt-BR','Albumina sérica'),
('ecat_0045','pt-PT','Albumina sérica'),
('ecat_0045','es-AR','Albúmina sérica'),
('ecat_0045','es-PY','Albúmina sérica'),
('ecat_0045','es','Albúmina sérica'),
('ecat_0045','en','Serum albumin'),
('ecat_0046','pt-BR','Proteínas totais e frações'),
('ecat_0046','pt-PT','Proteínas totais e frações'),
('ecat_0046','es-AR','Proteínas totales y fracciones'),
('ecat_0046','es-PY','Proteínas totales y fracciones'),
('ecat_0046','es','Proteínas totales y fracciones'),
('ecat_0046','en','Total protein and fractions'),
('ecat_0047','pt-BR','Amilase'),
('ecat_0047','pt-PT','Amilase'),
('ecat_0047','es-AR','Amilasa'),
('ecat_0047','es-PY','Amilasa'),
('ecat_0047','es','Amilasa'),
('ecat_0047','en','Amylase'),
('ecat_0048','pt-BR','Lipase'),
('ecat_0048','pt-PT','Lipase'),
('ecat_0048','es-AR','Lipasa'),
('ecat_0048','es-PY','Lipasa'),
('ecat_0048','es','Lipasa'),
('ecat_0048','en','Lipase'),
('ecat_0049','pt-BR','LDH (Lactato desidrogenase)'),
('ecat_0049','pt-PT','LDH (Lactato desidrogenase)'),
('ecat_0049','es-AR','LDH (Lactato deshidrogenasa)'),
('ecat_0049','es-PY','LDH (Lactato deshidrogenasa)'),
('ecat_0049','es','LDH (Lactato deshidrogenasa)'),
('ecat_0049','en','LDH (Lactate dehydrogenase)'),
('ecat_0050','pt-BR','CK total (Creatinoquinase)'),
('ecat_0050','pt-PT','CK total (Creatinoquinase)'),
('ecat_0050','es-AR','CK total (Creatinquinasa)'),
('ecat_0050','es-PY','CK total (Creatinquinasa)'),
('ecat_0050','es','CK total (Creatinquinasa)'),
('ecat_0050','en','Total CK (Creatine kinase)'),
('ecat_0051','pt-BR','Radiografia de tórax'),
('ecat_0051','pt-PT','Radiografia do tórax'),
('ecat_0051','es-AR','Radiografía de tórax'),
('ecat_0051','es-PY','Radiografía de tórax'),
('ecat_0051','es','Radiografía de tórax'),
('ecat_0051','en','Chest X-ray'),
('ecat_0052','pt-BR','Radiografia de coluna lombar'),
('ecat_0052','pt-PT','Radiografia da coluna lombar'),
('ecat_0052','es-AR','Radiografía de columna lumbar'),
('ecat_0052','es-PY','Radiografía de columna lumbar'),
('ecat_0052','es','Radiografía de columna lumbar'),
('ecat_0052','en','Lumbar spine X-ray'),
('ecat_0053','pt-BR','Radiografia de crânio'),
('ecat_0053','pt-PT','Radiografia do crânio'),
('ecat_0053','es-AR','Radiografía de cráneo'),
('ecat_0053','es-PY','Radiografía de cráneo'),
('ecat_0053','es','Radiografía de cráneo'),
('ecat_0053','en','Skull X-ray'),
('ecat_0054','pt-BR','Radiografia de abdome'),
('ecat_0054','pt-PT','Radiografia do abdómen'),
('ecat_0054','es-AR','Radiografía de abdomen'),
('ecat_0054','es-PY','Radiografía de abdomen'),
('ecat_0054','es','Radiografía de abdomen'),
('ecat_0054','en','Abdominal X-ray'),
('ecat_0055','pt-BR','Radiografia de membros superiores'),
('ecat_0055','pt-PT','Radiografia de membros superiores'),
('ecat_0055','es-AR','Radiografía de miembros superiores'),
('ecat_0055','es-PY','Radiografía de miembros superiores'),
('ecat_0055','es','Radiografía de miembros superiores'),
('ecat_0055','en','Upper limb X-ray'),
('ecat_0056','pt-BR','Radiografia de membros inferiores'),
('ecat_0056','pt-PT','Radiografia de membros inferiores'),
('ecat_0056','es-AR','Radiografía de miembros inferiores'),
('ecat_0056','es-PY','Radiografía de miembros inferiores'),
('ecat_0056','es','Radiografía de miembros inferiores'),
('ecat_0056','en','Lower limb X-ray'),
('ecat_0057','pt-BR','Mamografia bilateral'),
('ecat_0057','pt-PT','Mamografia bilateral'),
('ecat_0057','es-AR','Mamografía bilateral'),
('ecat_0057','es-PY','Mamografía bilateral'),
('ecat_0057','es','Mamografía bilateral'),
('ecat_0057','en','Bilateral mammography'),
('ecat_0058','pt-BR','Ultrassonografia de abdome total'),
('ecat_0058','pt-PT','Ecografia abdominal total'),
('ecat_0058','es-AR','Ecografía abdominal total'),
('ecat_0058','es-PY','Ecografía abdominal total'),
('ecat_0058','es','Ecografía abdominal total'),
('ecat_0058','en','Abdominal ultrasound'),
('ecat_0059','pt-BR','Ultrassonografia pélvica (transvaginal)'),
('ecat_0059','pt-PT','Ecografia pélvica (transvaginal)'),
('ecat_0059','es-AR','Ecografía pélvica (transvaginal)'),
('ecat_0059','es-PY','Ecografía pélvica (transvaginal)'),
('ecat_0059','es','Ecografía pélvica (transvaginal)'),
('ecat_0059','en','Pelvic ultrasound (transvaginal)'),
('ecat_0060','pt-BR','Ultrassonografia obstétrica'),
('ecat_0060','pt-PT','Ecografia obstétrica'),
('ecat_0060','es-AR','Ecografía obstétrica'),
('ecat_0060','es-PY','Ecografía obstétrica'),
('ecat_0060','es','Ecografía obstétrica'),
('ecat_0060','en','Obstetric ultrasound'),
('ecat_0061','pt-BR','Ultrassonografia de tireoide'),
('ecat_0061','pt-PT','Ecografia da tiroide'),
('ecat_0061','es-AR','Ecografía de tiroides'),
('ecat_0061','es-PY','Ecografía de tiroides'),
('ecat_0061','es','Ecografía de tiroides'),
('ecat_0061','en','Thyroid ultrasound'),
('ecat_0062','pt-BR','Ultrassonografia de mamas'),
('ecat_0062','pt-PT','Ecografia mamária'),
('ecat_0062','es-AR','Ecografía mamaria'),
('ecat_0062','es-PY','Ecografía mamaria'),
('ecat_0062','es','Ecografía mamaria'),
('ecat_0062','en','Breast ultrasound'),
('ecat_0063','pt-BR','Ultrassonografia de partes moles'),
('ecat_0063','pt-PT','Ecografia de partes moles'),
('ecat_0063','es-AR','Ecografía de partes blandas'),
('ecat_0063','es-PY','Ecografía de partes blandas'),
('ecat_0063','es','Ecografía de partes blandas'),
('ecat_0063','en','Soft tissue ultrasound'),
('ecat_0064','pt-BR','Tomografia computadorizada de crânio'),
('ecat_0064','pt-PT','Tomografia computorizada do crânio'),
('ecat_0064','es-AR','Tomografía computada de cráneo'),
('ecat_0064','es-PY','Tomografía computada de cráneo'),
('ecat_0064','es','Tomografía computarizada de cráneo'),
('ecat_0064','en','Head CT scan'),
('ecat_0065','pt-BR','Tomografia computadorizada de tórax'),
('ecat_0065','pt-PT','Tomografia computorizada do tórax'),
('ecat_0065','es-AR','Tomografía computada de tórax'),
('ecat_0065','es-PY','Tomografía computada de tórax'),
('ecat_0065','es','Tomografía computarizada de tórax'),
('ecat_0065','en','Chest CT scan'),
('ecat_0066','pt-BR','Tomografia computadorizada de abdome'),
('ecat_0066','pt-PT','Tomografia computorizada do abdómen'),
('ecat_0066','es-AR','Tomografía computada de abdomen'),
('ecat_0066','es-PY','Tomografía computada de abdomen'),
('ecat_0066','es','Tomografía computarizada de abdomen'),
('ecat_0066','en','Abdominal CT scan'),
('ecat_0067','pt-BR','Tomografia computadorizada de coluna'),
('ecat_0067','pt-PT','Tomografia computorizada da coluna'),
('ecat_0067','es-AR','Tomografía computada de columna'),
('ecat_0067','es-PY','Tomografía computada de columna'),
('ecat_0067','es','Tomografía computarizada de columna'),
('ecat_0067','en','Spine CT scan'),
('ecat_0068','pt-BR','Ressonância magnética de crânio'),
('ecat_0068','pt-PT','Ressonância magnética do crânio'),
('ecat_0068','es-AR','Resonancia magnética de cráneo'),
('ecat_0068','es-PY','Resonancia magnética de cráneo'),
('ecat_0068','es','Resonancia magnética de cráneo'),
('ecat_0068','en','Brain MRI'),
('ecat_0069','pt-BR','Ressonância magnética de coluna'),
('ecat_0069','pt-PT','Ressonância magnética da coluna'),
('ecat_0069','es-AR','Resonancia magnética de columna'),
('ecat_0069','es-PY','Resonancia magnética de columna'),
('ecat_0069','es','Resonancia magnética de columna'),
('ecat_0069','en','Spine MRI'),
('ecat_0070','pt-BR','Ressonância magnética de joelho'),
('ecat_0070','pt-PT','Ressonância magnética do joelho'),
('ecat_0070','es-AR','Resonancia magnética de rodilla'),
('ecat_0070','es-PY','Resonancia magnética de rodilla'),
('ecat_0070','es','Resonancia magnética de rodilla'),
('ecat_0070','en','Knee MRI'),
('ecat_0071','pt-BR','Ressonância magnética de ombro'),
('ecat_0071','pt-PT','Ressonância magnética do ombro'),
('ecat_0071','es-AR','Resonancia magnética de hombro'),
('ecat_0071','es-PY','Resonancia magnética de hombro'),
('ecat_0071','es','Resonancia magnética de hombro'),
('ecat_0071','en','Shoulder MRI'),
('ecat_0072','pt-BR','Ecocardiograma transtorácico'),
('ecat_0072','pt-PT','Ecocardiograma transtorácico'),
('ecat_0072','es-AR','Ecocardiograma transtorácico'),
('ecat_0072','es-PY','Ecocardiograma transtorácico'),
('ecat_0072','es','Ecocardiograma transtorácico'),
('ecat_0072','en','Transthoracic echocardiogram'),
('ecat_0073','pt-BR','Ecocardiograma com Doppler'),
('ecat_0073','pt-PT','Ecocardiograma com Doppler'),
('ecat_0073','es-AR','Ecocardiograma con Doppler'),
('ecat_0073','es-PY','Ecocardiograma con Doppler'),
('ecat_0073','es','Ecocardiograma con Doppler'),
('ecat_0073','en','Echocardiogram with Doppler'),
('ecat_0074','pt-BR','Doppler de carótidas'),
('ecat_0074','pt-PT','Doppler das carótidas'),
('ecat_0074','es-AR','Doppler de carótidas'),
('ecat_0074','es-PY','Doppler de carótidas'),
('ecat_0074','es','Doppler de carótidas'),
('ecat_0074','en','Carotid Doppler ultrasound'),
('ecat_0075','pt-BR','Densitometria óssea (DEXA)'),
('ecat_0075','pt-PT','Densitometria óssea (DEXA)'),
('ecat_0075','es-AR','Densitometría ósea (DEXA)'),
('ecat_0075','es-PY','Densitometría ósea (DEXA)'),
('ecat_0075','es','Densitometría ósea (DEXA)'),
('ecat_0075','en','Bone densitometry (DEXA)'),
('ecat_0076','pt-BR','Angiotomografia de coronárias'),
('ecat_0076','pt-PT','Angio-TC das coronárias'),
('ecat_0076','es-AR','Angiotomografía de coronarias'),
('ecat_0076','es-PY','Angiotomografía de coronarias'),
('ecat_0076','es','Angiotomografía de coronarias'),
('ecat_0076','en','Coronary CT angiography'),
('ecat_0077','pt-BR','Exame anatomopatológico (biópsia)'),
('ecat_0077','pt-PT','Exame anatomopatológico (biópsia)'),
('ecat_0077','es-AR','Estudio anatomopatológico (biopsia)'),
('ecat_0077','es-PY','Estudio anatomopatológico (biopsia)'),
('ecat_0077','es','Estudio anatomopatológico (biopsia)'),
('ecat_0077','en','Histopathology (biopsy)'),
('ecat_0078','pt-BR','Colpocitologia oncótica (Papanicolaou)'),
('ecat_0078','pt-PT','Colpocitologia oncológica (Papanicolaou)'),
('ecat_0078','es-AR','Citología cervical (Papanicolaou)'),
('ecat_0078','es-PY','Citología cervical (Papanicolaou)'),
('ecat_0078','es','Citología cervical (Papanicolaou)'),
('ecat_0078','en','Cervical cytology (Pap smear)'),
('ecat_0079','pt-BR','Imuno-histoquímica'),
('ecat_0079','pt-PT','Imuno-histoquímica'),
('ecat_0079','es-AR','Inmunohistoquímica'),
('ecat_0079','es-PY','Inmunohistoquímica'),
('ecat_0079','es','Inmunohistoquímica'),
('ecat_0079','en','Immunohistochemistry'),
('ecat_0080','pt-BR','Anatomopatológico intraoperatório (congelação)'),
('ecat_0080','pt-PT','Anatomopatológico intraoperatório (congelação)'),
('ecat_0080','es-AR','Anatomopatológico intraoperatorio (congelación)'),
('ecat_0080','es-PY','Anatomopatológico intraoperatorio (congelación)'),
('ecat_0080','es','Anatomopatológico intraoperatorio (congelación)'),
('ecat_0080','en','Intraoperative frozen section'),
('ecat_0081','pt-BR','Punção aspirativa por agulha fina (PAAF)'),
('ecat_0081','pt-PT','Punção aspirativa por agulha fina (PAAF)'),
('ecat_0081','es-AR','Punción aspirativa con aguja fina (PAAF)'),
('ecat_0081','es-PY','Punción aspirativa con aguja fina (PAAF)'),
('ecat_0081','es','Punción aspirativa con aguja fina (PAAF)'),
('ecat_0081','en','Fine needle aspiration (FNA)'),
('ecat_0082','pt-BR','Citologia de líquidos corporais'),
('ecat_0082','pt-PT','Citologia de líquidos corporais'),
('ecat_0082','es-AR','Citología de líquidos corporales'),
('ecat_0082','es-PY','Citología de líquidos corporales'),
('ecat_0082','es','Citología de líquidos corporales'),
('ecat_0082','en','Body fluid cytology'),
('ecat_0083','pt-BR','Biópsia de próstata (fragmentos)'),
('ecat_0083','pt-PT','Biópsia da próstata (fragmentos)'),
('ecat_0083','es-AR','Biopsia de próstata (fragmentos)'),
('ecat_0083','es-PY','Biopsia de próstata (fragmentos)'),
('ecat_0083','es','Biopsia de próstata (fragmentos)'),
('ecat_0083','en','Prostate biopsy (cores)'),
('ecat_0084','pt-BR','Histopatológico de placenta'),
('ecat_0084','pt-PT','Histopatológico da placenta'),
('ecat_0084','es-AR','Histopatológico de placenta'),
('ecat_0084','es-PY','Histopatológico de placenta'),
('ecat_0084','es','Histopatológico de placenta'),
('ecat_0084','en','Placental histopathology'),
('ecat_0085','pt-BR','Imunofluorescência direta'),
('ecat_0085','pt-PT','Imunofluorescência direta'),
('ecat_0085','es-AR','Inmunofluorescencia directa'),
('ecat_0085','es-PY','Inmunofluorescencia directa'),
('ecat_0085','es','Inmunofluorescencia directa'),
('ecat_0085','en','Direct immunofluorescence'),
('ecat_0086','pt-BR','Microscopia eletrônica'),
('ecat_0086','pt-PT','Microscopia eletrónica'),
('ecat_0086','es-AR','Microscopía electrónica'),
('ecat_0086','es-PY','Microscopía electrónica'),
('ecat_0086','es','Microscopía electrónica'),
('ecat_0086','en','Electron microscopy'),
('ecat_0087','pt-BR','Eletrocardiograma (ECG)'),
('ecat_0087','pt-PT','Eletrocardiograma (ECG)'),
('ecat_0087','es-AR','Electrocardiograma (ECG)'),
('ecat_0087','es-PY','Electrocardiograma (ECG)'),
('ecat_0087','es','Electrocardiograma (ECG)'),
('ecat_0087','en','Electrocardiogram (ECG)'),
('ecat_0088','pt-BR','Eletroencefalograma (EEG)'),
('ecat_0088','pt-PT','Eletroencefalograma (EEG)'),
('ecat_0088','es-AR','Electroencefalograma (EEG)'),
('ecat_0088','es-PY','Electroencefalograma (EEG)'),
('ecat_0088','es','Electroencefalograma (EEG)'),
('ecat_0088','en','Electroencephalogram (EEG)'),
('ecat_0089','pt-BR','Eletroneuromiografia (ENMG)'),
('ecat_0089','pt-PT','Eletroneuromiografia (ENMG)'),
('ecat_0089','es-AR','Electroneuromiografía (ENMG)'),
('ecat_0089','es-PY','Electroneuromiografía (ENMG)'),
('ecat_0089','es','Electroneuromiografía (ENMG)'),
('ecat_0089','en','Electromyography/nerve conduction (EMG/NCS)'),
('ecat_0090','pt-BR','Espirometria (prova de função pulmonar)'),
('ecat_0090','pt-PT','Espirometria (prova de função pulmonar)'),
('ecat_0090','es-AR','Espirometría (prueba de función pulmonar)'),
('ecat_0090','es-PY','Espirometría (prueba de función pulmonar)'),
('ecat_0090','es','Espirometría (prueba de función pulmonar)'),
('ecat_0090','en','Spirometry (pulmonary function test)'),
('ecat_0091','pt-BR','Teste ergométrico'),
('ecat_0091','pt-PT','Prova de esforço'),
('ecat_0091','es-AR','Prueba de esfuerzo'),
('ecat_0091','es-PY','Prueba de esfuerzo'),
('ecat_0091','es','Prueba de esfuerzo'),
('ecat_0091','en','Exercise stress test'),
('ecat_0092','pt-BR','Holter 24 horas'),
('ecat_0092','pt-PT','Holter 24 horas'),
('ecat_0092','es-AR','Holter de 24 horas'),
('ecat_0092','es-PY','Holter de 24 horas'),
('ecat_0092','es','Holter de 24 horas'),
('ecat_0092','en','24-hour Holter monitor'),
('ecat_0093','pt-BR','MAPA (Monitorização ambulatorial de pressão arterial)'),
('ecat_0093','pt-PT','MAPA (Monitorização ambulatória da pressão arterial)'),
('ecat_0093','es-AR','MAPA (Monitoreo ambulatorio de presión arterial)'),
('ecat_0093','es-PY','MAPA (Monitoreo ambulatorio de presión arterial)'),
('ecat_0093','es','MAPA (Monitorización ambulatoria de presión arterial)'),
('ecat_0093','en','ABPM (Ambulatory blood pressure monitoring)'),
('ecat_0094','pt-BR','Polissonografia'),
('ecat_0094','pt-PT','Polissonografia'),
('ecat_0094','es-AR','Polisomnografía'),
('ecat_0094','es-PY','Polisomnografía'),
('ecat_0094','es','Polisomnografía'),
('ecat_0094','en','Polysomnography (sleep study)'),
('ecat_0095','pt-BR','Triagem neonatal (teste do pezinho)'),
('ecat_0095','pt-PT','Rastreio neonatal (teste do pezinho)'),
('ecat_0095','es-AR','Tamizaje neonatal (test del talón)'),
('ecat_0095','es-PY','Cribado neonatal (test del talón)'),
('ecat_0095','es','Cribado neonatal (test del talón)'),
('ecat_0095','en','Newborn screening (heel prick test)'),
('ecat_0096','pt-BR','Audiometria'),
('ecat_0096','pt-PT','Audiometria'),
('ecat_0096','es-AR','Audiometría'),
('ecat_0096','es-PY','Audiometría'),
('ecat_0096','es','Audiometría'),
('ecat_0096','en','Audiometry'),
('ecat_0097','pt-BR','Colonoscopia'),
('ecat_0097','pt-PT','Colonoscopia'),
('ecat_0097','es-AR','Colonoscopía'),
('ecat_0097','es-PY','Colonoscopía'),
('ecat_0097','es','Colonoscopia'),
('ecat_0097','en','Colonoscopy'),
('ecat_0098','pt-BR','Endoscopia digestiva alta'),
('ecat_0098','pt-PT','Endoscopia digestiva alta'),
('ecat_0098','es-AR','Endoscopía digestiva alta'),
('ecat_0098','es-PY','Endoscopía digestiva alta'),
('ecat_0098','es','Endoscopia digestiva alta'),
('ecat_0098','en','Upper GI endoscopy (EGD)'),
('ecat_0099','pt-BR','Gasometria arterial'),
('ecat_0099','pt-PT','Gasometria arterial'),
('ecat_0099','es-AR','Gases arteriales'),
('ecat_0099','es-PY','Gases arteriales'),
('ecat_0099','es','Gasometría arterial'),
('ecat_0099','en','Arterial blood gas (ABG)'),
('ecat_0100','pt-BR','Teste alérgico cutâneo (prick test)'),
('ecat_0100','pt-PT','Teste cutâneo de alergia (prick test)'),
('ecat_0100','es-AR','Test cutáneo de alergia (prick test)'),
('ecat_0100','es-PY','Test cutáneo de alergia (prick test)'),
('ecat_0100','es','Test cutáneo de alergia (prick test)'),
('ecat_0100','en','Skin prick allergy test');